[build]
command = "yarn build" # the command you run to build this file
#functions = "/src/functions" # used for local
functions = "src/functions-dist" # used for builds
publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically

[[redirects]]
from = "/*"
to = "/index.html"
status = 200